[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

[secrets_scanning]
  omit_paths = [".firebaserc", "firebase.json", "database.rules.json"]