[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000

# Environment variables that should be omitted from secrets scanning
[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_FIREBASE_API_KEY,REACT_APP_FIREBASE_APP_ID,REACT_APP_FIREBASE_AUTH_DOMAIN,REACT_APP_FIREBASE_DATABASE_URL,REACT_APP_FIREBASE_MEASUREMENT_ID,REACT_APP_FIREBASE_MESSAGING_SENDER_ID,REACT_APP_FIREBASE_PROJECT_ID,REACT_APP_FIREBASE_STORAGE_BUCKET"
  SECRETS_SCAN_ENABLED = "false"

# Scheduled functions for automatic monitoring
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[plugins.inputs]
  # Monitor machines every 2 minutes
  schedule = "*/2 * * * *"
  function = "monitor-machines"
